import "server-only";

import type { ActionInputSchema } from "@/server/security/validate-action-input";

import {
  FAVORITE_LIMITS,
  type AddFavoriteInput,
  type RemoveFavoriteInput,
} from "./types";

/**
 * Listing ids are opaque strings from Firestore — alphanumeric + dashes
 * + underscores, generated by the SDK. The regex bounds the input
 * server-side so a malicious client cannot inject control characters
 * or path separators into the doc id.
 */
const LISTING_ID_REGEX = /^[A-Za-z0-9_-]{1,200}$/;
/** Same shape constraints as `preferredSlugSchema` in the biringas port. */
const LISTING_SLUG_REGEX = /^[a-z0-9-]{1,200}$/;

export const addFavoriteSchema: ActionInputSchema<AddFavoriteInput> = {
  parse(input: unknown): AddFavoriteInput {
    if (!input || typeof input !== "object") {
      throw new Error("addFavorite: input must be an object");
    }
    const r = input as Record<string, unknown>;

    const listingId = expectString(
      r.listingId,
      "listingId",
      FAVORITE_LIMITS.listingIdMax,
      LISTING_ID_REGEX,
    );
    const listingSlug = expectString(
      r.listingSlug,
      "listingSlug",
      FAVORITE_LIMITS.listingSlugMax,
      LISTING_SLUG_REGEX,
    );

    return { listingId, listingSlug };
  },
};

export const removeFavoriteSchema: ActionInputSchema<RemoveFavoriteInput> = {
  parse(input: unknown): RemoveFavoriteInput {
    if (!input || typeof input !== "object") {
      throw new Error("removeFavorite: input must be an object");
    }
    const r = input as Record<string, unknown>;
    const listingId = expectString(
      r.listingId,
      "listingId",
      FAVORITE_LIMITS.listingIdMax,
      LISTING_ID_REGEX,
    );
    return { listingId };
  },
};

function expectString(
  value: unknown,
  field: string,
  max: number,
  regex: RegExp,
): string {
  if (typeof value !== "string") {
    throw new Error(`favorites: ${field} must be a string`);
  }
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    throw new Error(`favorites: ${field} must not be empty`);
  }
  if (trimmed.length > max) {
    throw new Error(
      `favorites: ${field} must be at most ${max} character(s)`,
    );
  }
  if (!regex.test(trimmed)) {
    throw new Error(`favorites: ${field} contains invalid characters`);
  }
  return trimmed;
}
